/**
 * Phase 5.1a - Solver Bridge
 * Maps Physics Boundary Conditions and Loads to the IGA Solver.
 */

class SolverBridge {
    constructor(solver) {
        this.solver = solver;
    }

    /**
     * Solves the linear static system for a given patch
     * @param {object} patch - The NURBS patch (generated by factory)
     * @param {number} Tx    - Tension magnitude (N/mm^2)
     */
    solveLinearStatic(patch, Tx = 100.0) {
        const nU = patch.controlPoints.length;
        const nV = patch.controlPoints[0].length;
        
        // 1. Define Boundary Conditions (Symmetry)
        const bcs = [];
        
        // Bottom Edge (j=0): Symm in Y (u_y = 0)
        for (let i = 0; i < nU; i++) {
            bcs.push({ i, j: 0, axis: 'y', value: 0 });
        }
        
        // Left Edge (i=3 for 4x3 grid? No, i=3 is y-axis): Symm in X (u_x = 0)
        // In our factory, i=3 is the vertical edge (90 degrees)
        for (let j = 0; j < nV; j++) {
            bcs.push({ i: 3, j, axis: 'x', value: 0 });
        }

        // 2. Define Loads (Traction on Right Edge)
        // For simplicity in this first static step, we'll use point loads 
        // distributed along the right edge (i=0) or use the analytical traction assembly.
        const loads = [];
        const rightEdgeIdx = 0; // i=0 is 0 degrees (x-axis)
        
        // For the trainer, we can use the exact nodal traction if available,
        // or a simple point load distribution.
        for (let j = 0; j < nV; j++) {
            loads.push({ i: 0, j, fx: Tx / nV, fy: 0 });
        }

        // 3. Execute Solve
        const displacement = this.solver.solve(patch, bcs, loads);
        
        return {
            u: displacement,
            f_ext: Tx
        };
    }
}

window.SolverBridge = SolverBridge;
